spring.application.name=FlowPay
spring.datasource.url=jdbc:postgresql://localhost:5432/flowpay
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
