spring.application.name=FlowPay
server.address=0.0.0.0
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/flowpay
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
spring.rabbitmq.host=seu-host-rabbitmq
spring.rabbitmq.port=5671
spring.rabbitmq.username=seu_valor
spring.rabbitmq.password=seu_valor
spring.rabbitmq.virtual-host=seu_valor
spring.rabbitmq.ssl.enabled=true
flowpay.rabbit.enabled=true
flowpay.distribuicao.scheduler.enabled=true
flowpay.distribuicao.scheduler-delay-ms=5000
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.api-docs.version=OPENAPI_3_0
